chatterbox/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from . import views
from post import views as post_views


urlpatterns = [
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^$', post_views.post_list, name='post_list'),
    url(r'^company/$', views.get_company, name='get_company'),
    url(r'^guide/$', views.get_guide, name='get_guide'),
    url(r'^term/$', views.get_term, name='get_term'),
    url(r'^privacy/$', views.get_privacy, name='get_privacy'),

    url(r'^robots.txt$', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain"), name="project_robots_file"),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

member/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^mypage/$', views.my_page, name='my_page'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^delete/$', views.user_delete, name='user_delete'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^log/$', views.user_log, name='user_log'),
    url(r'^contact/create/$', views.create_chat, name='create_chat'),
    url(r'^get_liked_posts/$', views.get_liked_posts, name='get_liked_posts'),
    url(r'^toggle/$', views.get_toggle, name='get_toggle'),
]

post/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^views/$', views.post_list_views, name='post_list_views'),
    url(r'^comments/$', views.post_list_comments, name='post_list_comments'),
    url(r'^likes/$', views.post_list_likes, name='post_list_likes'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/update/$', views.post_update, name='post_update'),
    url(r'^(?P<post_pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    url(r'^(?P<post_pk>\d+)/share-count/$',
        views.add_share_count, name='add_share_count'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$',
        views.post_like_toggle, name='post_like_toggle'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^category/(?P<hierarchy>.+)/views$',
        views.show_category_views, name='show_category_views'),
    url(r'^category/(?P<hierarchy>.+)/comments$',
        views.show_category_comments, name='show_category_comments'),
    url(r'^category/(?P<hierarchy>.+)/likes$',
        views.show_category_likes, name='show_category_likes'),
    url(r'^search/$', views.search, name='search'),
]

member/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser, UserManager as BaseUserManager
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db import models


class UserManager(BaseUserManager):
    def create_superuser(self, *args, **kwargs):
        return super().create_superuser(gender=self.model.GENDER_OTHER, *args, **kwargs)


class User(AbstractUser):
    GENDER_MALE = 'm'
    GENDER_FEMALE = 'f'
    GENDER_OTHER = 'o'
    CHOICES_GENDER = (
        (GENDER_MALE, '남성'),
        (GENDER_FEMALE, '여성'),
        (GENDER_OTHER, '기타'),
    )
    profile_image = models.ImageField(
        default='default/user.png', null=True, upload_to='user')
    bio = models.CharField(max_length=160, null=True, blank=True)
    gender = models.CharField(
        max_length=1, choices=CHOICES_GENDER, null=True, blank=True)
    like_posts = models.ManyToManyField(
        'post.Post', blank=True, related_name='like_users')
    like_comments = models.ManyToManyField(
        'comment.Comment', blank=True, related_name='like_comments')
    hate_comments = models.ManyToManyField(
        'comment.Comment', blank=True, related_name='hate_comments')

    objects = UserManager()

    def __str__(self):
        return self.username


class ContactChat(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='owner')
    author = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='author')
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    content = models.TextField()

    @property
    def natural_time(self):
        return naturaltime(self.created_at)

    def __str__(self):
        return f'Chat (PK: {self.pk}, Author: {self.author.username})'

member/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import ContactChat


User = get_user_model()


class LoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['username'].label = '닉네임'
        class_update_fields = ['username', 'password']
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = User
        fields = (
            'username',
            'password',
        )


class SignupForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['username'].label = '닉네임'
        self.fields['password1'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '(영문 대소문자/숫자/특수문자 중 2가지 이상 조합, 8자~16자)'})
        self.fields['password2'].widget = forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder': '비밀번호를 다시 한 번 입력해주세요.'})
        class_update_fields = ['email', 'username', 'password1', 'password2', ]
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'password1',
            'password2',
        )
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'placeholder': '채터박스에서 익명으로 사용 하실 닉네임을 입력해주세요.',
                }
            ),
        }


class ProfileForm(forms.ModelForm):
    email = forms.EmailField(required=False)
    username = forms.CharField(required=False)
    bio = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['email'].label = 'E-mail'
        self.fields['username'].label = '닉네임'
        self.fields['bio'].label = '자기소개'
        class_update_fields = ['email', 'username', 'bio', ]
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update({
                'class': 'form-control'
            })

    class Meta:
        model = User
        fields = (
            'profile_image',
            'email',
            'username',
            'bio',
        )


class ContactChatForm(forms.ModelForm):
    class Meta:
        model = ContactChat
        fields = (
            'content',
        )
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'content',
                    'placeholder': '자유롭게 질문 또는 의견을 남겨주세요',
                }
            )
        }

member/views.py
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from itertools import chain
from django.contrib.auth import (
    authenticate,
    login as django_login,
    logout as django_logout,
)

from .models import ContactChat
from .forms import LoginForm, SignupForm, ProfileForm, ContactChatForm
from post import models as post_models
from comment import models as comment_models


def login(request):
    if request.user.is_authenticated():
        return redirect('post:post_list')
    else:
        if request.method == 'POST':
            # Data bounded form인스턴스 생성
            # AuthenticationForm의 첫 번째 인수는 해당 request가 되어야 한다
            login_form = LoginForm(request=request, data=request.POST)

            # 유효성 검증에 성공할 경우
            # AuthenticationForm을 사용하면 authenticate과정까지 완료되어야 유효성 검증을 통과한다
            if login_form.is_valid():
                # AuthenticatonForm에서 인증(authenticate)에 성공한 유저를 가져오려면 이 메서드를 사용한다
                user = login_form.get_user()
                # Django의 auth앱에서 제공하는 login함수를 실행해 앞으로의 요청/응답에 세션을 유지한다
                django_login(request, user)

                messages.success(
                    request, '<p><strong>{0}</strong>으로 로그인 되었습니다.</p>'.format(user.username))
                next = request.GET.get('next')
                return redirect(next if next else 'post:post_list')
        else:
            login_form = LoginForm()

        context = {
            'login_form': login_form,
        }
        return render(request, 'member/login.html', context)


@login_required
def logout(request):
    django_logout(request)
    messages.success(
        request, '<h4>로그아웃 되었습니다.</h4><p>채터박스는 익명으로 의견을 나누는 </p><p>[YES OR NO] 댓글 SNS입니다.</p><p>두 가지 중 선택이 어려울 때 질문하고 의견을 나누어보세요.</p>')
    return redirect('post:post_list')


def signup(request):
    if request.user.is_authenticated():
        return redirect('post:post_list')
    else:
        if request.method == 'POST':
            signup_form = SignupForm(request.POST, files=request.FILES)
            # 유효성 검증에 통과한 경우 (username의 중복과 password1, 2의 일치 여부)
            if signup_form.is_valid():
                # 유저를 생성 후 해당 User를 로그인 시킨다
                user = signup_form.save()

                messages.success(
                    request, '<h4>회원가입이 완료되었습니다.</h4><p>채터박스의 회원이 되신 것을 축하드립니다. </p><p>가입해주신 닉네임으로 로그인해주세요.</p>')
                return redirect('member:login')
        else:
            signup_form = SignupForm()

        context = {
            'signup_form': signup_form,
        }
        return render(request, 'member/signup.html', context)


@login_required
def my_page(request, backend='django.contrib.auth.backends.ModelBackend'):
    user = request.user

    if request.method == 'POST':
        profile_form = ProfileForm(
            request.POST, files=request.FILES, instance=user)

        if profile_form.is_valid():
            user = profile_form.save()
            messages.success(
                request, '<h4>프로필을 수정했어요!</h4><p>채터박스는 익명으로 의견을 나누는 [YES OR NO] 댓글 SNS입니다.</p><p>두 가지 중 선택이 어려울 때 질문하고 의견을 나누어보세요.</p>')
            django_login(
                request, user, backend='django.contrib.auth.backends.ModelBackend')
            return redirect('member:my_page')
    else:
        profile_form = ProfileForm(instance=user)

    context = {
        'user': user,
        'profile_form': profile_form,
    }
    return render(request, 'member/my_page.html', context)


@login_required
def password_change(request):
    if request.method == 'POST':
        password_form = PasswordChangeForm(request.user, request.POST)

        if password_form.is_valid():
            user = password_form.save()
            messages.success(
                request, '<h4>비밀번호를 변경했어요!</h4><p>채터박스는 익명으로 의견을 나누는 [YES OR NO] 댓글 SNS입니다.</p><p>두 가지 중 선택이 어려울 때 질문하고 의견을 나누어보세요.</p>')
            update_session_auth_hash(request, user)  # Important!
            return redirect('member:my_page')
    else:
        password_form = PasswordChangeForm(request.user)

    context = {
        'password_form': password_form,
    }
    return render(request, 'member/password_change.html', context)


@login_required
def user_delete(request):
    user = request.user

    if request.method == 'POST':
        user.delete()
        messages.success(
            request, '<h4>회원 탈퇴가 처리되었습니다.</h4><p>그 동안 채터박스를 이용해주셔서 감사합니다.</p>')
        return redirect('member:my_page')
    else:
        return redirect('member:my_page')


@login_required
def user_log(request):
    user = request.user
    sort = request.GET.get('sort', '')

    if sort == 'all_log':
        posts_log = post_models.Post.objects.filter(author=user)  # 내가 만든 채터박스
        comments_pro = comment_models.Comment.objects.filter(
            author=user, type=True)  # 내가 만든 찬성의견
        comments_con = comment_models.Comment.objects.filter(
            author=user, type=False)  # 내가 만든 반대의견
        likes_pro = user.like_comments.filter(type=True)  # 추천한 찬성 의견
        hates_pro = user.hate_comments.filter(type=True)  # 반대한 찬성 의견
        likes_con = user.like_comments.filter(type=False)  # 추천한 반대 의견
        hates_con = user.hate_comments.filter(type=False)  # 반대한 반대 의견
        comments_sorted = sorted(
            chain(comments_pro, comments_con), key=lambda instance: instance.created_at)
        lh_sorted = sorted(chain(likes_pro, hates_pro, likes_con,
                                 hates_con), key=lambda instance: instance.created_at)
        log_sorted = sorted(chain(posts_log, comments_sorted,
                                  lh_sorted), key=lambda instance: instance.created_at)
        context = {
            'posts_log': posts_log,
            'comments_pro': comments_pro,
            'comments_con': comments_con,
            'comments_sorted': comments_sorted,
            'likes_pro': likes_pro,
            'hates_pro': hates_pro,
            'likes_con': likes_con,
            'hates_con': hates_con,
            'lh_sorted': lh_sorted,
            'log_sorted': log_sorted,
            'sort': sort,
        }
        return render(request, 'member/log.html', context)
    elif sort == 'my_comments':
        comments_pro = comment_models.Comment.objects.filter(
            author=user, type=True)  # 내가 만든 찬성의견
        comments_con = comment_models.Comment.objects.filter(
            author=user, type=False)  # 내가 만든 반대의견
        comments_sorted = sorted(
            chain(comments_pro, comments_con), key=lambda instance: instance.created_at)
        log_sorted = comments_sorted
        context = {'comments_pro': comments_pro, 'comments_con': comments_con,
                   'comments_sorted': comments_sorted, 'log_sorted': log_sorted, 'sort': sort, }
        return render(request, 'member/log.html', context)
    elif sort == 'like_hate':
        likes_pro = user.like_comments.filter(type=True)  # 추천한 찬성 의견
        hates_pro = user.hate_comments.filter(type=True)  # 반대한 찬성 의견
        likes_con = user.like_comments.filter(type=False)  # 추천한 반대 의견
        hates_con = user.hate_comments.filter(type=False)  # 반대한 반대 의견
        lh_sorted = sorted(chain(likes_pro, hates_pro, likes_con,
                                 hates_con), key=lambda instance: instance.created_at)
        log_sorted = lh_sorted
        context = {'likes_pro': likes_pro, 'hates_pro': hates_pro, 'likes_con': likes_con,
                   'hates_con': hates_con, 'lh_sorted': lh_sorted, 'log_sorted': log_sorted, 'sort': sort, }
        return render(request, 'member/log.html', context)
    else:
        posts_log = post_models.Post.objects.filter(author=user)  # 내가 만든 채터박스
        log_sorted = posts_log
        context = {'posts_log': posts_log,
                   'log_sorted': log_sorted, 'sort': sort, }
    return render(request, 'member/log.html', context)


@login_required
def contact(request):
    user = request.user
    chats = ContactChat.objects.filter(owner=user)
    chat_form = ContactChatForm()

    context = {
        'user': user,
        'chats': chats,
        'chat_form': chat_form,
    }
    return render(request, 'member/contact.html', context)


@login_required
def create_chat(request):
    user = request.user

    if request.method == 'POST':
        chat_form = ContactChatForm(request.POST)
        if chat_form.is_valid():
            chat = chat_form.save(commit=False)
            chat.owner = request.user
            chat.author = request.user
            chat.save()
            return redirect('member:my_page')
        else:
            return redirect('member:my_page')


@login_required
def get_liked_posts(request):
    user = request.user
    liked_posts = user.like_posts.all()

    context = {
        'liked_posts': liked_posts,
    }
    return render(request, 'include/slide_menu.html', context)


@login_required
def get_toggle(request):
    return render(request, 'member/toggle.html')

templates/member/log.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Log{% endblock %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/member/my_page.css' %}">
<link rel="stylesheet" href="{% static 'css/member/log.css' %}">
<link rel="stylesheet" href="{% static 'css/post/post_list.css' %}">
{% endblock %}

{% block content %}
<nav class="lnb navbar">
    <div class="container">
        <a href="javascript:history.back()">
            <img class="nav-icon" src="{% static '/img/icons/back.png' %}" />
            <span class="highlight">MY PAGE</span>
        </a>
        <h3>활동 로그</h3>
        <ul class="navbar-nav flex-row"></ul>
    </div>
</nav>

<div class="row justify-content-center">
    <div class="col-md-7 p-0 mypage">
        <h2>My Page</h2>
        <div class="info-area">
            {% if user.bio %}
            <h6>{{ user.bio }}</h6>
            {% else %}
            <h6>자기소개가 비어있습니다.<br />간단하게 프로필을 작성해보아요!</h6>
            {% endif %}
            <a class="btn btn-gray" href="{% url 'member:logout' %}">LOG OUT</a>
        </div>

        <div class="mypage-body">
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item"><a class="tab-link" href="{% url 'member:my_page' %}">
                        <h5>프로필</h5>
                    </a></li>
                <li class="nav-item"><a class="tab-link active" href="#">
                        <h5>활동로그</h5>
                    </a></li>
                <li class="nav-item"><a class="tab-link" href="{% url 'member:contact' %}">
                        <h5>문의하기</h5>
                    </a></li>
            </ul>

            <div class="tab-pane" id="pills-log">
                <div class="mypage-header">
                    <h3>사람들과 소통한 기록 보기</h3>
                    <h6>채터박스를 만들거나 공유하거나<br />의견을 내거나 공감을 누르거나 했던<br />모든 활동을 볼 수 있어요.</h6>
                </div>

                <div class="form-group">
                    <select class="form-control sort-select" onchange="location = this.value;" name="?sort={{ sort }}">
                        <option value="?sort=all_log">모든 활동 보기</option>
                        <option value="?sort=my_posts">내가 만든 채터박스 보기</option>
                        <option value="?sort=my_comments">직접 남긴 의견 보기</option>
                        <option value="?sort=like_hate">추천/비추천한 의견 보기</option>
                    </select>
                </div>

                <div class="load-log">
                    {% if log_sorted %}
                    {% for log in log_sorted reversed %}
                    {% if log in posts_log %}
                    <div class="m60">
                        <div class="log-header">
                            <h3>채터박스를 만들었어요</h3>
                            <p>{{ log.natural_time }}</p>
                        </div>
                        <div class="log-body">
                            <label>Main Title</label>
                            <a href="{% url 'post:post_detail' post_pk=log.pk %}">
                                <h5>{{ log.title|truncatechars:40 }}</h5>
                            </a>
                            <label>Background</label>
                            <div class="background">
                                <a href="{% url 'post:post_detail' post_pk=log.pk %}">
                                    <h6>{{ log.background|safe|truncatechars:160 }}</h6>
                                </a>
                            </div>
                        </div>
                        <!-- <form class="btn-wrap row p-0" action="{% url 'post:post_delete' log.pk %}" method="post">
                                {% csrf_token %}
                                <div class="col-6"><a class="btn btn-fill btn-full" href="{% url 'post:post_update' log.pk %}">수정하기</a></div>
                                <div class="col-6"><input class="btn btn-gray btn-full" type="submit" value="삭제하기" onclick="return confirm('정말로 삭제할까요? \n\n게시물을 삭제하시면 해당 게시물의 \n모든 이력도 초기화 됩니다.')"></div>
                            </form> -->
                    </div>
                    {% endif %}
                    {% if log in comments_sorted %}
                    <div class="m60">
                        <div class="log-header">
                            <h3>직접 의견을 남겼어요</h3>
                            <p>{{ log.natural_time }}</p>
                        </div>
                        <div class="log-body">
                            <label>Main Title</label>
                            <a href="{% url 'post:post_detail' post_pk=log.post.pk %}">
                                <h5>{{ log.post.title }}</h5>
                                {% if log in comments_pro %}
                                <div class="post-title pro">
                                    {{ log.post.pro_title }}
                                </div>
                                {% endif %}
                                {% if log in comments_con %}
                                <div class="post-title con">
                                    {{ log.post.con_title }}
                                </div>
                                {% endif %}
                            </a>
                            <div class="background">
                                <div class="comment-header">
                                    {% if log.author.profile_image %}
                                    <img src="/media/{{ log.author.profile_image }}" alt="">
                                    {% else %}
                                    <img src="/media/default/user.png" alt="">
                                    {% endif %}
                                    <h6>{{ log.author }}<br /><span>{{ log.created_at }}</span></h6>
                                </div>
                                <h6>{{ log.content }}</h6>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% if log in lh_sorted %}
                    <div class="m60">
                        <div class="log-header">
                            <h3>의견을
                                {% if log in likes_pro or log in likes_con %}
                                추천했어요
                                {% endif %}
                                {% if log in hates_pro or log in hates_con %}
                                비추천했어요
                                {% endif %}
                            </h3>
                            <p>{{ log.natural_time }}</p>
                        </div>
                        <div class="log-body">
                            <label>Main Title</label>
                            <a href="{% url 'post:post_detail' post_pk=log.post.pk %}">
                                <h5>{{ log.post.title }}</h5>
                                {% if log in likes_pro or log in hates_pro %}
                                <div class="post-title pro">
                                    {{ log.post.pro_title }}
                                </div>
                                {% endif %}
                                {% if log in likes_con or log in hates_con %}
                                <div class="post-title con">
                                    {{ log.post.con_title }}
                                </div>
                                {% endif %}
                            </a>
                            <div class="background">
                                <div class="comment-header">
                                    {% if log.author.profile_image %}
                                    <img src="/media/{{ log.author.profile_image }}" alt="">
                                    {% else %}
                                    <img src="/media/default/user.png" alt="">
                                    {% endif %}
                                    <h6>{{ log.author }}<br /><span>{{ log.created_at }}</span></h6>
                                </div>
                                <h6>{{ log.content }}</h6>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                    {% else %}
                    <div class="empty">
                        <h3>활동 이력이 없습니다</h3>
                        <img src="{% static '/img/time-empty.png' %}" />
                        <p>채터박스에서 의견을 추천 또는 비추천하거나 <br />글을 남기는 등의 모든 활동 내역이 자동으로 표시됩니다.</p>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block customJS %}
<script type="text/javascript">
    $(document).ready(function () {
        var sort = $('.sort-select').attr('name');
        $('.sort-select option[value="' + sort + '"]').attr('selected', 'selected');
    });
</script>
{% endblock %}

templates/member/my_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}My Page{% endblock %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/member/my_page.css' %}">
{% endblock %}

{% block content %}
<nav class="lnb navbar">
    <div class="container">
        <a href="javascript:history.back()">
            <img class="nav-icon" src="{% static '/img/icons/back.png' %}" />
            <span class="highlight">MY PAGE</span>
        </a>
        <h3>프로필</h3>
        <ul class="navbar-nav flex-row"></ul>
    </div>
</nav>

<div class="row justify-content-center">
    <div class="col-md-7 p-0 mypage">
        <h2>My Page</h2>
        <div class="info-area">
            {% if user.bio %}
            <h6>{{ user.bio }}</h6>
            {% else %}
            <h6>자기소개가 비어있습니다.<br />간단하게 프로필을 작성해보아요!</h6>
            {% endif %}
            <a class="btn btn-gray" href="{% url 'member:logout' %}">LOG OUT</a>
        </div>

        <div class="mypage-body">
            <ul class="nav nav-pills nav-fill">
                <li class="nav-item"><a class="tab-link active" href="#">
                        <h5>프로필</h5>
                    </a></li>
                <li class="nav-item"><a class="tab-link" href="/member/log/?sort=all_log">
                        <h5>활동로그</h5>
                    </a></li>
                <li class="nav-item"><a class="tab-link" href="{% url 'member:contact' %}">
                        <h5>문의하기</h5>
                    </a></li>
            </ul>

            <div class="tab-pane" id="pills-profile">
                <div class="mypage-header">
                    <img id="previewHolder" class="profile_image" src="/media/{{ user.profile_image }}" />
                    <img class="fake-btn" src="{% static '/img/icons/camera.png' %}" />
                    <h4>{{ user }}</h4>
                </div>
                <div class="form-wrap">
                    {% include 'include/form.html' with form=profile_form submit_class='btn-full' submit_title='수정하기' enctype='file' %}
                </div>
                <div class="btn-wrap">
                    <h6>탈퇴를 원하시면 회원탈퇴 버튼을 눌러주세요</h6>
                    <a id="pw-change" class="btn btn-line" href="{% url 'member:password_change' %}">비밀번호 변경</a>
                    <form action="{% url 'member:user_delete' %}" method="post">
                        {% csrf_token %}
                        <input id="del-user" class="btn btn-gray" type="submit" value="회원 탈퇴"
                            onclick="return confirm('정말 삭제하시겠습니까?')">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block customJS %}
<script src="{% static 'js/include/image_preview.js' %}"></script>
{% endblock %}

templates/member/toggle.html
{% extends 'base.html' %}
{% load static %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/member/toggle.css' %}">
{% endblock %}

{% block content %}
<div class="toggle-header">
    <a href="javascript:history.back()">
        <h2>&times;</h2>
    </a>
</div>

<div class="toggle-wrap">
    <h2>MY PAGE</h2>
    {% if user.bio %}
    <h5>{{ user.bio }}</h5>
    {% else %}
    <h5>자기소개가 비어있습니다.<br />간단하게 프로필을 작성해보아요!</h5>
    {% endif %}
    <hr />
    <ul>
        <li>
            <a href="#" class="slide-trigger">
                <h5><img src="{% static '/img/icons/heart-fill.svg' %}" />좋아요</h5>
            </a>
        </li>
        <li>
            <a href="{% url 'member:my_page' %}">
                <h5><img src="{% static '/img/icons/profile.png' %}" />프로필</h5>
            </a>
        </li>
        <li>
            <a href="/member/log/?sort=all_log">
                <h5><img src="{% static '/img/icons/time-fill.png' %}" />활동로그</h5>
            </a>
        </li>
        <li>
            <a href="{% url 'member:contact' %}">
                <h5><img src="{% static '/img/icons/help-fill.png' %}" />문의하기</h5>
            </a>
        </li>
        <li>
            <a href="{% url 'member:logout' %}">
                <h5><img src="{% static '/img/icons/submit.png' %}" />LOG OUT</h5>
            </a>
        </li>
    </ul>
</div>
{% endblock %}