chatterbox/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from . import views
from post import views as post_views


urlpatterns = [
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^$', post_views.post_list, name='post_list'),
    url(r'^company/$', views.get_company, name='get_company'),
    url(r'^guide/$', views.get_guide, name='get_guide'),
    url(r'^term/$', views.get_term, name='get_term'),
    url(r'^privacy/$', views.get_privacy, name='get_privacy'),

    url(r'^robots.txt$', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain"), name="project_robots_file"),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

comment/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # Comment Url
    url(r'^(?P<comment_pk>\d+)/$', views.comment_detail, name='comment_detail'),
    url(r'^(?P<post_pk>\d+)/create/$',
        views.comment_create, name='comment_create'),
    url(r'^(?P<comment_pk>\d+)/update/$',
        views.comment_update, name='comment_update'),
    url(r'^delete/$', views.comment_delete, name='comment_delete'),

    # Comment on Comment Url
    url(r'^coc/(?P<coc_pk>\d+)/$', views.coc_detail, name='coc_detail'),
    url(r'^coc/$', views.coc_create, name='coc_create'),
    url(r'^coc/(?P<coc_pk>\d+)/update/$',
        views.coc_update, name='coc_update'),
    url(r'^coc/delete/$', views.coc_delete, name='coc_delete'),

    # Comment action Url
    url(r'^like-toggle/$', views.comment_like_toggle, name='comment_like_toggle'),
    url(r'^hate-toggle/$', views.comment_hate_toggle, name='comment_hate_toggle'),
    url(r'^(?P<comment_pk>\d+)/report/$',
        views.comment_report, name='comment_report'),
    url(r'^coc/(?P<coc_pk>\d+)/report/$', views.coc_report, name='coc_report'),
]

post/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^views/$', views.post_list_views, name='post_list_views'),
    url(r'^comments/$', views.post_list_comments, name='post_list_comments'),
    url(r'^likes/$', views.post_list_likes, name='post_list_likes'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/update/$', views.post_update, name='post_update'),
    url(r'^(?P<post_pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    url(r'^(?P<post_pk>\d+)/share-count/$',
        views.add_share_count, name='add_share_count'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$',
        views.post_like_toggle, name='post_like_toggle'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^category/(?P<hierarchy>.+)/views$',
        views.show_category_views, name='show_category_views'),
    url(r'^category/(?P<hierarchy>.+)/comments$',
        views.show_category_comments, name='show_category_comments'),
    url(r'^category/(?P<hierarchy>.+)/likes$',
        views.show_category_likes, name='show_category_likes'),
    url(r'^search/$', views.search, name='search'),
]

comment/models.py
from django.db import models
from django.conf import settings
from django.contrib.humanize.templatetags.humanize import naturaltime
from multiselectfield import MultiSelectField

from post import models as post_models


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta():
        abstract = True


class Comment(TimeStampedModel):
    post = models.ForeignKey(post_models.Post)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()
    type = models.BooleanField(default=True)

    @property
    def count_comment_likes(self):
        return self.like_comments.all().count()

    @property
    def count_comment_hates(self):
        return self.hate_comments.all().count()

    @property
    def natural_time(self):
        return naturaltime(self.created_at)

    def __str__(self):
        return f'Comment (PK: {self.pk}, Author: {self.author.username})'


class CommentOnComment(TimeStampedModel):
    comment = models.ForeignKey(
        Comment, blank=True, null=True, related_name='comment_on_comment')
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    content = models.TextField()

    @property
    def natural_time(self):
        return naturaltime(self.created_at)

    def __str__(self):
        return f'Comment (PK: {self.pk}, Author: {self.author.username})'


REPORT_CHOICES = (
    ('abuse', '심한 욕설을 포함하고 있어요 NO!'),
    ('infringement', '명예훼손/사생활침해 및 저작권침해!'),
    ('obscenity', '음란성 또는 청소년에게 매우 유해!'),
    ('Prosperity', '느닷없는 홍보 게시물 발견!'),
    ('irrelevant', '의견과 무관한 아무말 대잔치 댓글!'),
)


class ReportComment(TimeStampedModel):
    comment = models.ForeignKey(Comment, blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    report_reason = MultiSelectField(
        choices=REPORT_CHOICES, blank=True, null=True)
    etc_text = models.TextField(blank=True)


class ReportCommentOnComment(TimeStampedModel):
    comment_on_comment = models.ForeignKey(
        CommentOnComment, blank=True, null=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    report_reason = MultiSelectField(
        choices=REPORT_CHOICES, blank=True, null=True)
    etc_text = models.TextField(blank=True)

comment/forms.py
from django import forms

from .models import (
    Comment,
    CommentOnComment,
    ReportComment,
    ReportCommentOnComment,
)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': '동의하는 의견에 대한 생각 또는 이유를 알려주세요. \n추천을 많이 받을수록 상단으로 올라가요.',
                }
            )
        }


class CommentOnCommentForm(forms.ModelForm):
    class Meta:
        model = CommentOnComment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': '직접 입력',
                }
            )
        }


class ReportCommentForm(forms.ModelForm):
    class Meta:
        model = ReportComment
        fields = (
            'report_reason',
            'etc_text',
        )
        widgets = {
            'etc_text': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '신고 사유 직접 입력',
                }
            )
        }


class ReportCommentOnCommentForm(forms.ModelForm):
    class Meta:
        model = ReportCommentOnComment
        fields = (
            'report_reason',
            'etc_text',
        )
        widgets = {
            'etc_text': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '신고 사유 직접 입력',
                }
            )
        }

comment/views.py
import json
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from utils.decorators import login_required
from django.db.models import Count, Q

from .models import Comment, CommentOnComment
from .forms import CommentForm, CommentOnCommentForm, ReportCommentForm, ReportCommentOnCommentForm
from post import models as post_models


def comment_detail(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment_on_comment_form = CommentOnCommentForm()
    return render(request, 'include/comment.html', {'comment': comment, 'comment_on_comment_form': comment_on_comment_form})


@login_required
def comment_create(request, post_pk):
    if request.method == 'POST':
        type = request.POST.get('type', None)
        post = get_object_or_404(post_models.Post, pk=post_pk)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            if type == "con":
                comment.type = False
            comment.save()
            comment_on_comment_form = CommentOnCommentForm()
            return render(request, 'include/comment.html', {'comment': comment, 'comment_on_comment_form': comment_on_comment_form})

    return redirect('post:post_detail', post_pk=post_pk)


@login_required
def comment_update(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    post_pk = comment.post.pk

    if comment.author != request.user:
        return redirect('post:post_detail', post_pk=post_pk)
    else:
        if request.method == 'POST':
            comment_form = CommentForm(
                request.POST, request.FILES, instance=comment)

            if comment_form.is_valid():
                comment = comment_form.save()
        else:
            comment_form = CommentForm(instance=comment)

    context = {
        'comment': comment,
        'comment_form': comment_form,
    }
    return render(request, 'comment/comment_update.html', context)


@login_required
def comment_delete(request):
    comment_pk = request.POST.get('comment_pk', None)
    comment = get_object_or_404(Comment, pk=comment_pk)

    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '댓글이 삭제되었습니다.'
    else:
        message = '잘못된 접근입니다.'
    return HttpResponse(json.dumps({'message': message}), content_type="application/json")


def coc_detail(request, coc_pk):
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)

    return render(request, 'include/coc.html', {'coc': coc})


@login_required
def coc_create(request):
    if request.method == 'POST':
        comment_pk = request.POST.get('comment_pk', None)
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment_on_comment_form = CommentOnCommentForm(request.POST)

        if comment_on_comment_form.is_valid():
            coc = comment_on_comment_form.save(commit=False)
            coc.comment = comment
            coc.author = request.user
            coc.save()
            return render(request, 'include/coc.html', {'coc': coc})
    else:
        context = {
            'comment_on_comment_form': comment_on_comment_form,
        }
        return render(request, 'comment/coc_create.html', context)


@login_required
def coc_update(request, coc_pk):
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)

    if coc.author != request.user:
        post_pk = coc.comment.post.pk
        return redirect('post:post_detail', post_pk=post_pk)
    else:
        if request.method == 'POST':
            comment_on_comment_form = CommentOnCommentForm(
                request.POST, request.FILES, instance=coc)

            if comment_on_comment_form.is_valid():
                comment = comment_on_comment_form.save()
        else:
            comment_on_comment_form = CommentOnCommentForm(instance=coc)

    context = {
        'coc': coc,
        'comment_on_comment_form': comment_on_comment_form,
    }
    return render(request, 'comment/coc_update.html', context)


@login_required
def coc_delete(request):
    coc_pk = request.POST.get('coc_pk', None)
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)

    if request.method == 'POST' and request.user == coc.author:
        coc.delete()
        message = '댓글이 삭제되었습니다.'
    else:
        message = '잘못된 접근입니다.'
    return HttpResponse(json.dumps({'message': message}), content_type="application/json")


@login_required
def comment_like_toggle(request):
    comment_pk = request.POST.get('comment_pk', None)
    comment = get_object_or_404(Comment, pk=comment_pk)
    filtered_like_comments = request.user.like_comments.filter(pk=comment.pk)
    filtered_hate_comments = request.user.hate_comments.filter(pk=comment.pk)

    if filtered_hate_comments.exists():
        message = '이미 비추천하신 의견에는 추천을 누를 수 없습니다.'
        result = False
    else:
        if filtered_like_comments.exists():
            request.user.like_comments.remove(comment)
            message = '좋아요를 취소하셨어요!'
        else:
            request.user.like_comments.add(comment)
            message = '의견을 좋아하셨어요!'
        result = True

    return HttpResponse(json.dumps({'message': message, 'result': result}), content_type="application/json")


@login_required
def comment_hate_toggle(request):
    comment_pk = request.POST.get('comment_pk', None)
    comment = get_object_or_404(Comment, pk=comment_pk)
    filtered_hate_comments = request.user.hate_comments.filter(pk=comment.pk)
    filtered_like_comments = request.user.like_comments.filter(pk=comment.pk)

    if filtered_like_comments.exists():
        message = '이미 추천하신 의견에는 비추천을 누를 수 없습니다.'
        result = False
    else:
        if filtered_hate_comments.exists():
            request.user.hate_comments.remove(comment)
            message = '싫어요를 취소하셨어요!'
        else:
            request.user.hate_comments.add(comment)
            message = '의견을 싫어하셨어요!'
        result = True

    return HttpResponse(json.dumps({'message': message, 'result': result}), content_type="application/json")


@login_required
def comment_report(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    post_pk = comment.post.pk

    if request.method == 'POST':
        report_comment_form = ReportCommentForm(request.POST)

        if report_comment_form.is_valid():
            report_comment = report_comment_form.save(commit=False)
            report_comment.comment = comment
            report_comment.author = request.user
            report_comment.save()
            messages.success(
                request, '<h4>신고가 접수되었어요.</h4><p>신고가 성공적으로 접수되었습니다.</p><p>신고해주신 내용으로 검토 후 삭제 등 조치 예정입니다.</p>')
            return redirect('post:post_detail', post_pk=post_pk)
    else:
        report_comment_form = ReportCommentForm()

    context = {
        'comment': comment,
        'report_comment_form': report_comment_form,
    }
    return render(request, 'comment/comment_report.html', context)


@login_required
def coc_report(request, coc_pk):
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)
    post_pk = coc.comment.post.pk

    if request.method == 'POST':
        report_coc_form = ReportCommentOnCommentForm(request.POST)

        if report_coc_form.is_valid():
            report_coc = report_coc_form.save(commit=False)
            report_coc.comment_on_comment = coc
            report_coc.author = request.user
            report_coc.save()
            messages.success(
                request, '<h4>신고가 접수되었어요.</h4><p>신고가 성공적으로 접수되었습니다.</p><p>신고해주신 내용으로 검토 후 삭제 등 조치 예정입니다.</p>')
            return redirect('post:post_detail', post_pk=post_pk)
    else:
        report_coc_form = ReportCommentOnCommentForm()

    context = {
        'coc': coc,
        'report_coc_form': report_coc_form,
    }
    return render(request, 'comment/coc_report.html', context)

templates/comment/coc_update.html
{% load static %}
<div class="coc-update form-wrap">
    {{ comment_on_comment_form.content }}
    <button id="btn-coc-clear-{{ coc.pk }}" class="btn btn-line coc-clear-btn">취소하기</button>
    <button id="btn-coc-update-{{ coc.pk }}" class="btn btn-fill">수정하기</button>

    <script type="text/javascript">
        $('#btn-coc-update-{{ coc.pk }}').click(function () {
            var content = $('.coc-update input').val();
            var $target = $(this).parent().parent().parent();
            if (content.length > 256) {
                alert('댓글은 최대 256자 입력 가능합니다. 현재 글자수 :' + content.length)
                return;
            }
            $.ajax({
                type: 'POST',
                url: '{% url "comment:coc_update" coc_pk=coc.pk %}',
                data: {
                    'content': content,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: 'html',
                success: function (data, textStatus, jqXHR) {
                    $target.load('{% url "comment:coc_detail" coc_pk=coc.pk %}');
                    $('.toast .content').html('<p>댓글을 수정하셨습니다.</p>');
                    $('.toast').toast('show');
                }
            })
        });

        $('#btn-coc-clear-{{ coc.pk }}').click(function () {
            var $target = $(this).parent().parent().parent();
            $target.load('{% url "comment:coc_detail" coc_pk=coc.pk %}');
        });
    </script>
</div>

templates/comment/comment_list.html
{% load static %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/comment/comment.css' %}">
<link rel="stylesheet" href="{% static 'css/comment/comment_action.css' %}">
{% endblock %}

<!-- @@@@@@@@@@@@@@@@ COMMENT TITLE START @@@@@@@@@@@@@@@@ -->
<div class="row comment_title p-0">
    <div class="col-6 pro-title comment-toggle {% if not user.is_authenticated %}plzLogin{% endif %}"
        data-toggle="collapse" data-target="#pro-form">
        <h5>{{ post.pro_title }}</h5>
        <img class="add-pro" src="{% static '/img/icons/add-pro.svg' %}" />
    </div>
    <div class="col-6 con-title comment-toggle {% if not user.is_authenticated %}plzLogin{% endif %}"
        data-toggle="collapse" data-target="#con-form">
        <h5>{{ post.con_title }}</h5>
        <img class="add-con" src="{% static '/img/icons/add-con.svg' %}" />
    </div>
</div>
<!-- @@@@@@@@@@@@@@@@ COMMENT TITLE END @@@@@@@@@@@@@@@@ -->

<div class="row comment-wrap p-0">
    <div class="pro-comments col-6 p-0">
        <!-- @@@@@@@@@@@@@@@@ PRO COMMENT CREATE START @@@@@@@@@@@@@@@@ -->
        {% if user.is_authenticated %}
        <div id="pro-form" class="form-wrap pro-form collapse">
            {{ comment_form.content }}
            <h6 id="pro-comment-count" class="comment-count">0</h6>
            <button class="btn btn-line" type="button"><a data-toggle="collapse" href="#pro-form">취소하기</a></button>
            <button class="btn btn-fill comment-create" name="pro">등록하기</button>
        </div>
        {% endif %}
        <!-- @@@@@@@@@@@@@@@@ PRO COMMENT CREATE END @@@@@@@@@@@@@@@@ -->
        <!-- @@@@@@@@@@@@@@@@ PRO COMMENT LIST START @@@@@@@@@@@@@@@@ -->
        <div class="comment-list pro-list">
            <ul class="mine">
                {% for comment in procomments_mine.all %}
                <li class="comment">{% include 'include/comment.html' %}</li>
                {% if forloop.last %}
                <div class="comment-divider pro-divider">
                    <hr>
                    <span>나의 등록 의견</span>
                    <hr>
                </div>
                {% endif %}
                {% endfor %}
            </ul>
            <ul class="etc">
                {% for comment in procomments_exclude.all %}
                <li class="comment">{% include 'include/comment.html' %}</li>
                {% endfor %}
            </ul>
        </div>
        <!-- @@@@@@@@@@@@@@@@ PRO COMMENT LIST END @@@@@@@@@@@@@@@@ -->
    </div>

    <div class="con-comments col-6 p-0">
        <!-- @@@@@@@@@@@@@@@@ CON COMMENT CREATE START @@@@@@@@@@@@@@@@ -->
        {% if user.is_authenticated %}
        <div id="con-form" class="form-wrap con-form collapse">
            {{ comment_form.content }}
            <h6 id="con-comment-count" class="comment-count">0</h6>
            <button class="btn btn-line" type="button"><a data-toggle="collapse" href="#con-form">취소하기</a></button>
            <button class="btn btn-fill comment-create" name="con">등록하기</button>
        </div>
        {% endif %}
        <!-- @@@@@@@@@@@@@@@@ CON COMMENT CREATE END @@@@@@@@@@@@@@@@ -->
        <!-- @@@@@@@@@@@@@@@@ CON COMMENT LIST START @@@@@@@@@@@@@@@@ -->
        <div class="comment-list con-list">
            <ul class="mine">
                {% for comment in concomments_mine.all %}
                <li class="comment">{% include 'include/comment.html' %}</li>
                {% if forloop.last %}
                <div class="comment-divider con-divider">
                    <hr>
                    <span>나의 등록 의견</span>
                    <hr>
                </div>
                {% endif %}
                {% endfor %}
            </ul>
            <ul class="etc">
                {% for comment in concomments_exclude.all %}
                <li class="comment">{% include 'include/comment.html' %}</li>
                {% endfor %}
            </ul>
        </div>
        <!-- @@@@@@@@@@@@@@@@ CON COMMENT LIST END @@@@@@@@@@@@@@@@ -->
    </div>
</div>

{% include 'include/toast.html' %}
{% include 'include/modal.html' with modal_id='reportModal' modal_title='신고하기' modal_btn='신고하기' %}

{% block customJS %}
<script type="text/javascript">
    $(document).on('click', '.comment-create', function () {
        var content = $(this).parent().find('textarea').val();
        var type = $(this).attr('name');
        if (content.length > 256) {
            alert('의견은 최대 256자 입력 가능합니다. 현재 글자수 :' + content.length)
            return;
        }
        if (content.length == 0) {
            alert('의견 내용을 입력해주세요! 현재 글자수 :' + content.length)
            return;
        } else {
            $.ajax({
                type: 'POST',
                url: '{% url "comment:comment_create" post_pk=post.pk %}',
                data: {
                    'content': content,
                    'type': type,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: 'html',
                success: function (data, textStatus, jqXHR) {
                    $('.form-wrap textarea').val('');
                    if (type == 'pro') {
                        if ($('.pro-list .mine .comment')[0]) {
                            $('.pro-list .mine').prepend('<li class="comment">' + data + '</li>');
                        } else {
                            $('.pro-list .mine').prepend('<li class="comment">' + data + '</li>');
                            $('.pro-list .mine').append('<div class="comment-divider pro-divider"><hr><span>나의 등록 의견</span><hr></div>');
                        };
                    } else {
                        if ($('.con-list .mine .comment')[0]) {
                            $('.con-list .mine').prepend('<li class="comment">' + data + '</li>');
                        } else {
                            $('.con-list .mine').prepend('<li class="comment">' + data + '</li>');
                            $('.con-list .mine').append('<div class="comment-divider con-divider"><hr><span>나의 등록 의견</span><hr></div>');
                        };
                    }
                    $('.toast .content').html('<p>의견을 작성하셨습니다.</p><p>자신의 의견은 최상단에 표시됩니다.</p>');
                    $('.toast').toast('show');
                }
            });
        };
    });

    $(document).on('click', '.comment-delete', function () {
        if (!confirm('정말로 삭제할까요? \n\n의견을 삭제하시면 해당 의견의 \n추천/비추천 등 이력도 초기화 됩니다.')) { return };
        var pk = $(this).attr('name');
        var $target = $(this).parent().parent().parent();
        $.ajax({
            type: "POST",
            url: "{% url 'comment:comment_delete' %}",
            data: {
                'comment_pk': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: "json",
            success: function (response) {
                $target.remove();
                if ($('.pro-list .mine .comment')[0]) { } else { $('.pro-divider').fadeOut(); };
                if ($('.con-list .mine .comment')[0]) { } else { $('.con-divider').fadeOut(); };
                alert(response.message);
            }
        });
    });

    $(document).on('click', '.coc-create', function () {
        var content = $(this).parent().find('textarea').val();
        var pk = $(this).attr('name');
        var $target = $('.count-' + pk);
        if (content.length > 256) {
            alert('댓글은 최대 256자 입력 가능합니다. 현재 글자수 :' + content.length)
            return;
        }
        if (content.length == 0) {
            alert('의견 내용을 입력해주세요! 현재 글자수 :' + content.length)
            return;
        } else {
            $.ajax({
                type: 'POST',
                url: '{% url "comment:coc_create" %}',
                data: {
                    'content': content,
                    'comment_pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: 'html',
                success: function (data, textStatus, jqXHR) {
                    var changeNum = Number($target.text()) + 1;
                    $target.text(changeNum);
                    $('.coc-form textarea').val('');
                    $('#action-' + pk + ' .coc-list').prepend('<div class="coc-item">' + data + '</div>');
                    $('#action-' + pk + ' .coc-empty').hide();
                    $('.toast .content').html('<p>댓글을 작성하셨습니다.</p>');
                    $('.toast').toast('show');
                }
            });
        };
    });

    $(document).on('click', '.coc-delete', function () {
        if (!confirm('정말로 삭제할까요? \n\n의견을 삭제하시면 해당 의견의 \n모든 이력도 초기화 됩니다.')) { return };
        var pk = $(this).attr('name');
        var $target = $(this).parent().parent().parent();
        $.ajax({
            type: "POST",
            url: "{% url 'comment:coc_delete' %}",
            data: {
                'coc_pk': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: "json",
            success: function (response) {
                $target.remove();
                alert(response.message);
            }
        });
    });

    $(document).on('click', '.comment-like', function () {
        var pk = $(this).attr('name');
        var $target = $(this).find('p');
        $.ajax({
            type: "POST",
            url: "{% url 'comment:comment_like_toggle' %}",
            data: {
                'comment_pk': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: "json",
            success: function (response) {
                $('.toast .content').html('<p>' + response.message + '</p>');
                $('.toast').toast('show');
                if (response.result) {
                    if ($target.hasClass('active')) {
                        var changeNum = Number($target.text()) - 1;
                        $target.text(changeNum);
                        $target.removeClass('active');
                        $target.parent().children('img').attr('src', '{% static "/img/icons/like-hate-empty.png" %}');
                    } else {
                        var changeNum = Number($target.text()) + 1;
                        $target.text(changeNum);
                        $target.addClass('active');
                        $target.parent().children('img').attr('src', '{% static "/img/icons/like-hate-fill.png" %}');
                    }
                }
            }
        });
    });

    $(document).on('click', '.comment-hate', function () {
        var pk = $(this).attr('name');
        var $target = $(this).find('p');
        $.ajax({
            type: "POST",
            url: "{% url 'comment:comment_hate_toggle' %}",
            data: {
                'comment_pk': pk,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            dataType: "json",
            success: function (response) {
                $('.toast .content').html('<p>' + response.message + '</p>');
                $('.toast').toast('show');
                if (response.result) {
                    if ($target.hasClass('active')) {
                        var changeNum = Number($target.text()) - 1;
                        $target.text(changeNum);
                        $target.removeClass('active');
                        $target.parent().children('img').attr('src', '{% static "/img/icons/like-hate-empty.png" %}');
                    } else {
                        var changeNum = Number($target.text()) + 1;
                        $target.text(changeNum);
                        $target.addClass('active');
                        $target.parent().children('img').attr('src', '{% static "/img/icons/like-hate-fill.png" %}');
                    }
                }
            }
        });
    });
</script>
{% endblock %}