chatterbox/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from . import views
from post import views as post_views


urlpatterns = [
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^$', post_views.post_list, name='post_list'),
    url(r'^company/$', views.get_company, name='get_company'),
    url(r'^guide/$', views.get_guide, name='get_guide'),
    url(r'^term/$', views.get_term, name='get_term'),
    url(r'^privacy/$', views.get_privacy, name='get_privacy'),

    url(r'^robots.txt$', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain"), name="project_robots_file"),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

comment/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    # Comment Url
    url(r'^(?P<comment_pk>\d+)/$', views.comment_detail, name='comment_detail'),
    url(r'^(?P<post_pk>\d+)/create/$',
        views.comment_create, name='comment_create'),
    url(r'^(?P<comment_pk>\d+)/update/$',
        views.comment_update, name='comment_update'),
    url(r'^delete/$', views.comment_delete, name='comment_delete'),

    # Comment on Comment Url
    url(r'^coc/(?P<coc_pk>\d+)/$', views.coc_detail, name='coc_detail'),
    url(r'^coc/$', views.coc_create, name='coc_create'),
    url(r'^coc/(?P<coc_pk>\d+)/update/$',
        views.coc_update, name='coc_update'),
    url(r'^coc/delete/$', views.coc_delete, name='coc_delete'),

    # Comment action Url
    url(r'^like-toggle/$', views.comment_like_toggle, name='comment_like_toggle'),
    url(r'^hate-toggle/$', views.comment_hate_toggle, name='comment_hate_toggle'),
    url(r'^(?P<comment_pk>\d+)/report/$',
        views.comment_report, name='comment_report'),
    url(r'^coc/(?P<coc_pk>\d+)/report/$', views.coc_report, name='coc_report'),
]

member/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^mypage/$', views.my_page, name='my_page'),
    url(r'^password_change/$', views.password_change, name='password_change'),
    url(r'^delete/$', views.user_delete, name='user_delete'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^log/$', views.user_log, name='user_log'),
    url(r'^contact/create/$', views.create_chat, name='create_chat'),
    url(r'^get_liked_posts/$', views.get_liked_posts, name='get_liked_posts'),
    url(r'^toggle/$', views.get_toggle, name='get_toggle'),
]

post/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^views/$', views.post_list_views, name='post_list_views'),
    url(r'^comments/$', views.post_list_comments, name='post_list_comments'),
    url(r'^likes/$', views.post_list_likes, name='post_list_likes'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/update/$', views.post_update, name='post_update'),
    url(r'^(?P<post_pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    url(r'^(?P<post_pk>\d+)/share-count/$',
        views.add_share_count, name='add_share_count'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$',
        views.post_like_toggle, name='post_like_toggle'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^category/(?P<hierarchy>.+)/views$',
        views.show_category_views, name='show_category_views'),
    url(r'^category/(?P<hierarchy>.+)/comments$',
        views.show_category_comments, name='show_category_comments'),
    url(r'^category/(?P<hierarchy>.+)/likes$',
        views.show_category_likes, name='show_category_likes'),
    url(r'^search/$', views.search, name='search'),
]

comment/forms.py
from django import forms

from .models import (
    Comment,
    CommentOnComment,
    ReportComment,
    ReportCommentOnComment,
)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': '동의하는 의견에 대한 생각 또는 이유를 알려주세요. \n추천을 많이 받을수록 상단으로 올라가요.',
                }
            )
        }


class CommentOnCommentForm(forms.ModelForm):
    class Meta:
        model = CommentOnComment
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': '직접 입력',
                }
            )
        }


class ReportCommentForm(forms.ModelForm):
    class Meta:
        model = ReportComment
        fields = (
            'report_reason',
            'etc_text',
        )
        widgets = {
            'etc_text': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '신고 사유 직접 입력',
                }
            )
        }


class ReportCommentOnCommentForm(forms.ModelForm):
    class Meta:
        model = ReportCommentOnComment
        fields = (
            'report_reason',
            'etc_text',
        )
        widgets = {
            'etc_text': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '신고 사유 직접 입력',
                }
            )
        }

post/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        class_update_fields = [
            'title',
            'background',
            'background_image1',
            'background_image2',
            'background_image3',
            'background_image4',
            'background_image5',
            'pro_title',
            'con_title',
            'tag',
            'category',
        ]
        for field_name in class_update_fields:
            self.fields[field_name].widget.attrs.update(
                {'class': 'form-control'})

    class Meta:
        model = Post
        fields = (
            'title',
            'background',
            'background_image1',
            'background_image2',
            'background_image3',
            'background_image4',
            'background_image5',
            'pro_title',
            'con_title',
            'tag',
            'category',
        )
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': '주제 또는 제목을 입력해주세요. (8자 이상 입력해주세요)', }),
            'background': forms.Textarea(attrs={'placeholder': '질문에 대한 더 많은 배경 정보를 알려주세요. \n상세히 적을수록 다양하고 명확한 의견을 들을 수 있어요. \n(50자 이상 입력해주세요)', }),
            'pro_title': forms.TextInput(attrs={'placeholder': '첫 번째 의견을 입력해주세요. (4자 이상 입력해주세요)', }),
            'con_title': forms.TextInput(attrs={'placeholder': '두 번째 의견을 입력해주세요. (4자 이상 입력해주세요)', }),
            'category': forms.Select(attrs={'placeholder': '카테고리를 선택해주세요.', }),
            'tag': forms.TextInput(attrs={'placeholder': '태그는 쉼표나 공백으로 분리됩니다.', }),
        }

comment/views.py
import json
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from utils.decorators import login_required
from django.db.models import Count, Q

from .models import Comment, CommentOnComment
from .forms import CommentForm, CommentOnCommentForm, ReportCommentForm, ReportCommentOnCommentForm
from post import models as post_models


def comment_detail(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    comment_on_comment_form = CommentOnCommentForm()
    return render(request, 'include/comment.html', {'comment': comment, 'comment_on_comment_form': comment_on_comment_form})


@login_required
def comment_create(request, post_pk):
    if request.method == 'POST':
        type = request.POST.get('type', None)
        post = get_object_or_404(post_models.Post, pk=post_pk)
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.author = request.user
            if type == "con":
                comment.type = False
            comment.save()
            comment_on_comment_form = CommentOnCommentForm()
            return render(request, 'include/comment.html', {'comment': comment, 'comment_on_comment_form': comment_on_comment_form})

    return redirect('post:post_detail', post_pk=post_pk)


@login_required
def comment_update(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    post_pk = comment.post.pk

    if comment.author != request.user:
        return redirect('post:post_detail', post_pk=post_pk)
    else:
        if request.method == 'POST':
            comment_form = CommentForm(
                request.POST, request.FILES, instance=comment)

            if comment_form.is_valid():
                comment = comment_form.save()
        else:
            comment_form = CommentForm(instance=comment)

    context = {
        'comment': comment,
        'comment_form': comment_form,
    }
    return render(request, 'comment/comment_update.html', context)


@login_required
def comment_delete(request):
    comment_pk = request.POST.get('comment_pk', None)
    comment = get_object_or_404(Comment, pk=comment_pk)

    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '댓글이 삭제되었습니다.'
    else:
        message = '잘못된 접근입니다.'
    return HttpResponse(json.dumps({'message': message}), content_type="application/json")


def coc_detail(request, coc_pk):
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)

    return render(request, 'include/coc.html', {'coc': coc})


@login_required
def coc_create(request):
    if request.method == 'POST':
        comment_pk = request.POST.get('comment_pk', None)
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment_on_comment_form = CommentOnCommentForm(request.POST)

        if comment_on_comment_form.is_valid():
            coc = comment_on_comment_form.save(commit=False)
            coc.comment = comment
            coc.author = request.user
            coc.save()
            return render(request, 'include/coc.html', {'coc': coc})
    else:
        context = {
            'comment_on_comment_form': comment_on_comment_form,
        }
        return render(request, 'comment/coc_create.html', context)


@login_required
def coc_update(request, coc_pk):
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)

    if coc.author != request.user:
        post_pk = coc.comment.post.pk
        return redirect('post:post_detail', post_pk=post_pk)
    else:
        if request.method == 'POST':
            comment_on_comment_form = CommentOnCommentForm(
                request.POST, request.FILES, instance=coc)

            if comment_on_comment_form.is_valid():
                comment = comment_on_comment_form.save()
        else:
            comment_on_comment_form = CommentOnCommentForm(instance=coc)

    context = {
        'coc': coc,
        'comment_on_comment_form': comment_on_comment_form,
    }
    return render(request, 'comment/coc_update.html', context)


@login_required
def coc_delete(request):
    coc_pk = request.POST.get('coc_pk', None)
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)

    if request.method == 'POST' and request.user == coc.author:
        coc.delete()
        message = '댓글이 삭제되었습니다.'
    else:
        message = '잘못된 접근입니다.'
    return HttpResponse(json.dumps({'message': message}), content_type="application/json")


@login_required
def comment_like_toggle(request):
    comment_pk = request.POST.get('comment_pk', None)
    comment = get_object_or_404(Comment, pk=comment_pk)
    filtered_like_comments = request.user.like_comments.filter(pk=comment.pk)
    filtered_hate_comments = request.user.hate_comments.filter(pk=comment.pk)

    if filtered_hate_comments.exists():
        message = '이미 비추천하신 의견에는 추천을 누를 수 없습니다.'
        result = False
    else:
        if filtered_like_comments.exists():
            request.user.like_comments.remove(comment)
            message = '좋아요를 취소하셨어요!'
        else:
            request.user.like_comments.add(comment)
            message = '의견을 좋아하셨어요!'
        result = True

    return HttpResponse(json.dumps({'message': message, 'result': result}), content_type="application/json")


@login_required
def comment_hate_toggle(request):
    comment_pk = request.POST.get('comment_pk', None)
    comment = get_object_or_404(Comment, pk=comment_pk)
    filtered_hate_comments = request.user.hate_comments.filter(pk=comment.pk)
    filtered_like_comments = request.user.like_comments.filter(pk=comment.pk)

    if filtered_like_comments.exists():
        message = '이미 추천하신 의견에는 비추천을 누를 수 없습니다.'
        result = False
    else:
        if filtered_hate_comments.exists():
            request.user.hate_comments.remove(comment)
            message = '싫어요를 취소하셨어요!'
        else:
            request.user.hate_comments.add(comment)
            message = '의견을 싫어하셨어요!'
        result = True

    return HttpResponse(json.dumps({'message': message, 'result': result}), content_type="application/json")


@login_required
def comment_report(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    post_pk = comment.post.pk

    if request.method == 'POST':
        report_comment_form = ReportCommentForm(request.POST)

        if report_comment_form.is_valid():
            report_comment = report_comment_form.save(commit=False)
            report_comment.comment = comment
            report_comment.author = request.user
            report_comment.save()
            messages.success(
                request, '<h4>신고가 접수되었어요.</h4><p>신고가 성공적으로 접수되었습니다.</p><p>신고해주신 내용으로 검토 후 삭제 등 조치 예정입니다.</p>')
            return redirect('post:post_detail', post_pk=post_pk)
    else:
        report_comment_form = ReportCommentForm()

    context = {
        'comment': comment,
        'report_comment_form': report_comment_form,
    }
    return render(request, 'comment/comment_report.html', context)


@login_required
def coc_report(request, coc_pk):
    coc = get_object_or_404(CommentOnComment, pk=coc_pk)
    post_pk = coc.comment.post.pk

    if request.method == 'POST':
        report_coc_form = ReportCommentOnCommentForm(request.POST)

        if report_coc_form.is_valid():
            report_coc = report_coc_form.save(commit=False)
            report_coc.comment_on_comment = coc
            report_coc.author = request.user
            report_coc.save()
            messages.success(
                request, '<h4>신고가 접수되었어요.</h4><p>신고가 성공적으로 접수되었습니다.</p><p>신고해주신 내용으로 검토 후 삭제 등 조치 예정입니다.</p>')
            return redirect('post:post_detail', post_pk=post_pk)
    else:
        report_coc_form = ReportCommentOnCommentForm()

    context = {
        'coc': coc,
        'report_coc_form': report_coc_form,
    }
    return render(request, 'comment/coc_report.html', context)

templates/include/category.html
{% load static %}
<div class="category-wrap">
    <div class="category m60" name="{{ target }}">
        <a id="all" class="category-link" href="{% url 'post:post_list' %}" onclick="showModal();">
            <img class="category-icon" src="{% static '/img/categories/all.png' %}" />
            <h6>ALL</h6>
        </a>

        {% for category in categories %}
        <a id="{{ category.slug }}" class="category-link" href="/post/category/{{ category.slug }}"
            onclick="showModal();">
            <img class="category-icon" src="/static/img/categories/{{ category.slug }}.png" />
            <h6>{{ category.name }}</h6>
        </a>
        {% endfor %}
    </div>
    <div class="category-paddles">
        <button class="category-paddle category-paddle-left"><img
                src="{% static '/img/categories/left.svg' %}"></button>
        <button class="category-paddle category-paddle-right"><img style="transform: rotate(180deg);"
                src="{% static '/img/categories/left.svg' %}"></button>
    </div>
</div>

<script>
    $(document).ready(function () {
        var category = $('.category').attr('name');
        if (category.length) {
            $('#' + category).addClass('active');
        } else {
            $('#all').addClass('active');
        }

        $('.category-paddle-left').click(function (event) {
            event.preventDefault();
            $('.category').animate({
                scrollLeft: "-=64px"
            }, "fast");
        });
        $('.category-paddle-right').click(function (event) {
            event.preventDefault();
            $('.category').animate({
                scrollLeft: "+=64px"
            }, "fast");
        });
    });
</script>

templates/include/coc.html
{% load static %}
<div class="item-header comment-header">
    <div class="header-left">
        <img src="/media/{{ coc.author.profile_image }}" />
        <h6>{{ coc.author }}<br><span>{{ coc.natural_time }}</span></h6>
    </div>
    <div class="header-right">
        {% if user.is_authenticated %}
        <a href="#reportModal" data-toggle="modal" onclick="$('#reportModal .modal-content').load('{% url 'comment:coc_report' coc_pk=coc.pk %}');">
            <img src="{% static '/img/icons/report.png' %}" /><span>신고</span>
        </a>
        {% endif %}
        {% if coc.author == request.user %}
        <a class="coc-update" onclick="$('.coc-clear-btn').click();$('#coc-content-{{ coc.pk }}').load('{% url 'comment:coc_update' coc_pk=coc.pk %}');">
            <img src="{% static '/img/icons/edit.png' %}">수정
        </a>
        <a class="coc-delete" name="{{ coc.pk }}">
            <img src="{% static '/img/icons/delete.png' %}" />삭제
        </a>
        {% endif %}
    </div>
</div>
<h6 id="coc-content-{{ coc.pk }}">{{ coc.content }}</h6>

templates/include/comment.html
{% load static %}
<div class="comment-header">
    <div class="header-left">
        <img src="{{ comment.author.profile_image.url }}" />
        <h6>{{ comment.author }}<br><span>{{ comment.natural_time }}</span></h6>
    </div>
    <div class="header-right">
        {% if comment.author == request.user %}
        <a
            onclick="$('.clear-btn').click();$('#content-{{ comment.pk }}').load('{% url 'comment:comment_update' comment_pk=comment.pk %}');"><img
                src="{% static '/img/icons/edit.png' %}">수정하기</a>
        <a class="comment-delete" name="{{ comment.pk }}"><img src="{% static '/img/icons/delete.png' %}" />삭제하기</a>
        {% endif %}
    </div>
</div>

<h6 id="content-{{ comment.pk }}" class="comment-content">{{ comment.content|linebreaks }}</h6>

<div class="comment-footer">
    <div class="btn-wrap">
        <div class="like-hate">
            <button class="comment-like {% if not user.is_authenticated %}plzLogin{% endif %}" name="{{ comment.pk }}">
                {% if comment in user.like_comments.all %}
                <img src="{% static '/img/icons/like-hate-fill.png' %}" />
                <p class="count active"> {{ comment.like_comments.count }}</p>
                {% else %}
                <img src="{% static '/img/icons/like-hate-empty.png' %}" />
                <p class="count"> {{ comment.like_comments.count }}</p>
                {% endif %}
            </button>
        </div>

        <div class="like-hate">
            <button class="comment-hate {% if not user.is_authenticated %}plzLogin{% endif %}" name="{{ comment.pk }}">
                {% if comment in user.hate_comments.all %}
                <img class="hate" src="{% static '/img/icons/like-hate-fill.png' %}" />
                <p class="count active">{{ comment.hate_comments.count }}</p>
                {% else %}
                <img class="hate" src="{% static '/img/icons/like-hate-empty.png' %}" />
                <p class="count">{{ comment.hate_comments.count }}</p>
                {% endif %}
            </button>
        </div>
    </div>

    <!-- @@@@@@@@@@@@@@@@ PRO COMMENT'COMMENT N REPORT TOGGLE START @@@@@@@@@@@@@@@@ -->
    <div class="btn-wrap">
        <button class="coc-toggle {{ comment.pk }}-toggle collapsed" data-toggle="collapse"
            data-target="#action-{{ comment.pk }}">
            <img src="{% static '/img/icons/comment.png' %}" />
            <span class="count count-{{ comment.pk }}">{{ comment.comment_on_comment.count }}</span>
        </button>
        {% if user.is_authenticated %}
        <button data-toggle="modal" data-target="#reportModal"
            onclick="$('#reportModal .modal-content').load('{% url 'comment:comment_report' comment_pk=comment.pk %}');">
            <img src="{% static '/img/icons/report.png' %}" />
            <span class="count web-flex">신고하기</span>
        </button>
        {% endif %}
    </div>
    <!-- @@@@@@@@@@@@@@@@ PRO COMMENT'COMMENT N REPORT TOGGLE END @@@@@@@@@@@@@@@@ -->
</div>

<!-- @@@@@@@@@@@@@@@@ PRO COMMENT'COMMENT N REPORT CONTENT START @@@@@@@@@@@@@@@@ -->
<div class="comment-action collapse" id="action-{{ comment.pk }}">
    {% if user.is_authenticated %}
    <div class="coc-form" name="{{ comment.pk }}">
        {{ comment_on_comment_form.content }}
        <h6 id="coc-count-{{ comment.pk }}" class="coc-count">0</h6>
        <button class="btn btn-fill coc-create" name="{{ comment.pk }}">등록하기</button>
    </div>
    {% endif %}

    <div class="coc-list">
        {% if comment.comment_on_comment.exists %}
        {% for coc in comment.comment_on_comment.all reversed %}
        <div class="coc-item">{% include 'include/coc.html' %}</div>
        {% endfor %}
        {% else %}
        <h6 class="coc-empty text-center my-3">등록 된 대댓글이 없습니다.</h6>
        {% endif %}
    </div>
    <button class="coc-fold mt-2" data-toggle="collapse" data-target="#action-{{ comment.pk }}" name="{{ comment.pk }}">
        <img src="{% static '/img/icons/down.png' %}" alt="">
        <p>접기</p>
    </button>
</div>
<!-- @@@@@@@@@@@@@@@@ PRO COMMENT'COMMENT N REPORT CONTENT END @@@@@@@@@@@@@@@@ -->

templates/include/navbar.html
{% load static %}
<nav class="gnb navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'post:post_list' %}" onclick="showModal();">
            <img class="nav-logo" src="{% static '/img/logo.svg' %}" />
        </a>

        <ul class="navbar-nav ml-auto flex-row">
            <li class="nav-item"><a class="nav-link" href="{% url 'post:search' %}"><img class="nav-icon x2"
                        src="{% static '/img/icons/search-fill.svg' %}" /></a></li>
            <li class="nav-item web-flex" style="margin-right: 8px;"><a class="nav-link slide-trigger" href="#"><img
                        class="nav-icon" src="{% static '/img/icons/heart-fill.svg' %}" /></a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="btn btn-fill" href="{% url 'post:post_create' %}">CREATE</a></li>
            <li class="nav-item web-flex"><a class="btn btn-line" href="{% url 'member:my_page' %}">MY PAGE</a></li>
            <li class="nav-item mobile-flex"><a class="nav-link" href="{% url 'member:get_toggle' %}"><img
                        class="toggle-btn nav-icon x2" src="{% static '/img/icons/toggle.svg' %}"
                        style="margin-left: 4px;" /></a></li>
            {% else %}
            <li class="nav-item web-flex">
                <a class="btn btn-fill" href="{% url 'member:login' %}?next={{ request.path }}">LOG IN</a>
            </li>
            <li class="nav-item mobile-flex">
                <a class="nav-link" href="{% url 'member:login' %}?next={{ request.path }}">
                    <img class="nav-icon x2" src="{% static '/img/icons/user-fill.svg' %}" />
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/include/share.html
{% load static %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/include/share.css' %}">
{% endblock %}

<div class="share-sns">
    <a href="javascript:shareFacebook()">
        <img src="{% static '/img/share-fb.svg' %}" />
    </a>

    <a href="javascript:shareNaver()">
        <img src="{% static '/img/share-naver.svg' %}" />
    </a>

    <a href="javascript:shareKatalk()">
        <img src="{% static '/img/share-kakao.svg' %}" />
    </a>

    <a href="javascript:shareLink()">
        <img src="{% static '/img/share-link.svg' %}" />
    </a>
    <input type="text" value="Copy Url" id="linkInput">
</div>

{% block customJS %}
<script src="//developers.kakao.com/sdk/js/kakao.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/clipboard.js/1.5.10/clipboard.min.js"></script>
<script src="{% static 'js/include/share.js' %}"></script>
<script>
    // ADD SHARE COUNT BY JUST CLICK
    $(document).ready(function () {
        $(document).on('click', '.share-sns a', function () {
            $.ajax({ url: "{% url 'post:add_share_count' post.pk %}", });
        });
    });
</script>
{% endblock %}

templates/include/slide_menu.html
{% load static %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/include/slide_menu.css' %}">
{% endblock %}

{% block content %}
<nav id="slide-menu">
    <div class="inner">
        <div class="slide-header">
            <h3 class="slide-close">&times;</h3>
            <h4>좋아요</h4>
        </div>
        <div class="slide-body">
            {% if liked_posts %}
            {% for post in liked_posts %}
            <div class="like-card">
                <div class="btn-area" onclick="return confirm('좋아요 목록에서 제외하기 \n\n제외하시면 좋아요 목록에서 사라집니다. \n이후에 다시 찜하면 목록에 표시 됩니다.')">
                    <form action="{% url 'post:post_like_toggle' post_pk=post.pk %}" method="POST">
                        {% csrf_token %}
                        <button class="del-like">
                            <h3>&times;</h3>
                        </button>
                    </form>
                </div>

                <label>Title</label>
                <a href="{% url 'post:post_detail' post_pk=post.id %}">
                    <h3>{{ post.title }}</h3>
                </a>
                <div class="subtitle-wrap clearfix">
                    <div class="pro-title float-left"></div>
                    <p class="float-right">{{ post.pro_title }}</p>
                </div>
                <div class="subtitle-wrap clearfix">
                    <div class="con-title float-left"></div>
                    <p class="float-right">{{ post.con_title }}</p>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="likes-empty">
                <h4>찜 목록이 없습니다.</h4>
                <img src="{% static '/img/heart-empty.png' %}" />
            </div>
            {% endif %}
        </div>
    </div>
</nav>
{% endblock %}

templates/include/sort.html
{% load static %}
<div class="col-12">
    <div class="sort-button" name="{{ sort }}">
        <a class="select-change" href="{% url 'post:post_list' %}">
            <h5 id="new">최신순</h5>
        </a>
        <a class="select-change" href="{% url 'post:post_list_views' %}">
            <h5 id="views">조회순</h5>
        </a>
        <a class="select-change" href="{% url 'post:post_list_comments' %}">
            <h5 id="comments">댓글순</h5>
        </a>
        <a class="select-change" href="{% url 'post:post_list_likes' %}">
            <h5 id="likes">지금 인기</h5>
        </a>
    </div>
</div>

<script>
    $('.select-change').click(function () {
        showModal();
    });

    $(document).ready(function () {
        var sort = $('.sort-button').attr('name');
        if (sort.length) {
            $('#' + sort).addClass('active');
        } else {
            $('#new').addClass('active');
        }
    });
</script>