chatterbox/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from . import views
from post import views as post_views


urlpatterns = [
    url(r'^post/', include('post.urls', namespace='post')),
    url(r'^comment/', include('comment.urls', namespace='comment')),
    url(r'^member/', include('member.urls', namespace='member')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^admin/', admin.site.urls),

    url(r'^$', post_views.post_list, name='post_list'),
    url(r'^company/$', views.get_company, name='get_company'),
    url(r'^guide/$', views.get_guide, name='get_guide'),
    url(r'^term/$', views.get_term, name='get_term'),
    url(r'^privacy/$', views.get_privacy, name='get_privacy'),

    url(r'^robots.txt$', TemplateView.as_view(
        template_name="robots.txt", content_type="text/plain"), name="project_robots_file"),
]

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

post/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^views/$', views.post_list_views, name='post_list_views'),
    url(r'^comments/$', views.post_list_comments, name='post_list_comments'),
    url(r'^likes/$', views.post_list_likes, name='post_list_likes'),
    url(r'^create/$', views.post_create, name='post_create'),
    url(r'^(?P<post_pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^(?P<post_pk>\d+)/update/$', views.post_update, name='post_update'),
    url(r'^(?P<post_pk>\d+)/delete/$', views.post_delete, name='post_delete'),

    url(r'^(?P<post_pk>\d+)/share-count/$',
        views.add_share_count, name='add_share_count'),
    url(r'^(?P<post_pk>\d+)/like-toggle/$',
        views.post_like_toggle, name='post_like_toggle'),
    url(r'^category/(?P<hierarchy>.+)/$', views.show_category, name='category'),
    url(r'^category/(?P<hierarchy>.+)/views$',
        views.show_category_views, name='show_category_views'),
    url(r'^category/(?P<hierarchy>.+)/comments$',
        views.show_category_comments, name='show_category_comments'),
    url(r'^category/(?P<hierarchy>.+)/likes$',
        views.show_category_likes, name='show_category_likes'),
    url(r'^search/$', views.search, name='search'),
]

post/models.py
from django.db import models
from django.conf import settings
from django.contrib.humanize.templatetags.humanize import naturaltime
from tagging.fields import TagField


class TimeStampedModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)

    class Meta():
        abstract = True


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    parent = models.ForeignKey(
        'self', blank=True, null=True, related_name='children')

    class Meta:
        # enforcing that there can not be two
        unique_together = ('slug', 'parent',)
        verbose_name_plural = "categories"  # categories under a parent with same slug

    def __str__(self):                          # __str__ method elaborated later in
        # post.  use __unicode__ in place of
        full_path = [self.name]
        k = self.parent                         # __str__ if you are using python 2

        while k is not None:
            full_path.append(k.name)
            k = k.parent

        return ' -> '.join(full_path[::-1])


class Post(TimeStampedModel):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    category = models.ForeignKey('Category')

    title = models.CharField(max_length=160, null=True)
    background = models.TextField()
    background_image1 = models.ImageField(
        upload_to='post', blank=True, null=True)
    background_image2 = models.ImageField(
        upload_to='post', blank=True, null=True)
    background_image3 = models.ImageField(
        upload_to='post', blank=True, null=True)
    background_image4 = models.ImageField(
        upload_to='post', blank=True, null=True)
    background_image5 = models.ImageField(
        upload_to='post', blank=True, null=True)
    tag = TagField()

    view_count = models.PositiveSmallIntegerField(default=0)
    share_count = models.PositiveSmallIntegerField(default=0)

    pro_title = models.CharField(max_length=160, null=True)
    con_title = models.CharField(max_length=160, null=True)

    @property
    def natural_time(self):
        return naturaltime(self.created_at)

    @property
    def likes_count(self):
        return self.like_users.all().count()

    @property
    def comment_count(self):
        all_count = self.comment_set.count()
        return all_count

    @property
    def pro_count(self):
        pro_sum = self.comment_set.filter(type=True).count()
        pro_comments = self.comment_set.filter(type=True)
        for comment in pro_comments:
            pro_sum = pro_sum + comment.count_comment_likes
        return pro_sum

    @property
    def con_count(self):
        con_sum = self.comment_set.filter(type=False).count()
        con_comments = self.comment_set.filter(type=False)
        for comment in con_comments:
            con_sum = con_sum + comment.count_comment_likes
        return con_sum

    @property
    def all_count(self):
        return self.pro_count + self.con_count

    @property
    def pro_percent(self):
        if not self.all_count == 0:
            result = self.pro_count / self.all_count
        else:
            result = 0
        return result

    @property
    def con_percent(self):
        if not self.all_count == 0:
            result = self.con_count / self.all_count
        else:
            result = 0
        return result

    def get_cat_list(self):
        k = self.category
        breadcrumb = [""]
        while k is not None:
            breadcrumb.append(k.slug)
            k = k.parent

        for i in range(len(breadcrumb)-1):
            breadcrumb[i] = '/'.join(breadcrumb[-1:i-1:-1])
        return breadcrumb[-1:0:-1]

    def __str__(self):
        return f'Post (PK: {self.pk}, Author: {self.author.username})'

    class Meta:
        ordering = ['-created_at']

post/views.py
import json
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from utils.decorators import login_required
from django.db.models import Count, Q, Func, F

from .models import Post, Category
from .forms import PostForm
from tagging.models import Tag
from comment import models as comment_models
from comment import forms as comment_forms


def search(request):
    q = request.GET.get('q', '')
    tags = Tag.objects.annotate(tags_count=Count(
        'items')).order_by('-tags_count')[:28]

    posts = Post.objects.filter(Q(title__icontains=q) | Q(tag__icontains=q))
    search_count = posts.count()

    context = {
        'q': q,
        'tags': tags,
        'posts': posts,
        'search_count': search_count,
    }
    return render(request, 'post/search.html', context)


def show_category(request, hierarchy=None):
    sort = 'new'
    categories = Category.objects.all()
    category_slug = hierarchy.split('/')
    category_queryset = list(categories)
    all_slugs = [x.slug for x in category_queryset]
    parent = None

    for slug in category_slug:
        if slug in all_slugs:
            target = slug
            parent = get_object_or_404(Category, slug=slug, parent=parent)
            posts = parent.post_set.order_by('-created_at')

    paginator = Paginator(posts, 10)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'sub_categories': parent.children.all(),
        'categories': categories,
        'target': target,
        'sort': sort,
    }
    return render(request, "post/category_list.html", context)


def show_category_views(request, hierarchy=None):
    sort = 'views'
    categories = Category.objects.all()
    category_slug = hierarchy.split('/')
    category_queryset = list(categories)
    all_slugs = [x.slug for x in category_queryset]
    parent = None

    for slug in category_slug:
        if slug in all_slugs:
            target = slug
            parent = get_object_or_404(Category, slug=slug, parent=parent)
            posts = parent.post_set.order_by('-view_count')

    paginator = Paginator(posts, 10)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'sub_categories': parent.children.all(),
        'categories': categories,
        'target': target,
        'sort': sort,
    }
    return render(request, "post/category_list.html", context)


def show_category_comments(request, hierarchy=None):
    sort = 'comments'
    categories = Category.objects.all()
    category_slug = hierarchy.split('/')
    category_queryset = list(categories)
    all_slugs = [x.slug for x in category_queryset]
    parent = None

    for slug in category_slug:
        if slug in all_slugs:
            target = slug
            parent = get_object_or_404(Category, slug=slug, parent=parent)
            posts = parent.post_set.annotate(count=Count(
                'comment')).order_by('-count')

    paginator = Paginator(posts, 10)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'sub_categories': parent.children.all(),
        'categories': categories,
        'target': target,
        'sort': sort,
    }
    return render(request, "post/category_list.html", context)


def show_category_likes(request, hierarchy=None):
    sort = 'likes'
    categories = Category.objects.all()
    category_slug = hierarchy.split('/')
    category_queryset = list(categories)
    all_slugs = [x.slug for x in category_queryset]
    parent = None

    for slug in category_slug:
        if slug in all_slugs:
            target = slug
            parent = get_object_or_404(Category, slug=slug, parent=parent)
            posts = parent.post_set.annotate(like_count=Count(
                'like_users')).order_by('-like_count')

    paginator = Paginator(posts, 10)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'posts': posts,
        'sub_categories': parent.children.all(),
        'categories': categories,
        'target': target,
        'sort': sort,
    }
    return render(request, "post/category_list.html", context)


def post_list(request):
    sort = 'new'
    categories = Category.objects.all()
    posts = Post.objects.order_by('-created_at')

    paginator = Paginator(posts, 12)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'categories': categories, 'sort': sort, }
    return render(request, 'post/post_list.html', context)


def post_list_views(request):
    sort = 'views'
    categories = Category.objects.all()
    posts = Post.objects.order_by('-view_count')

    paginator = Paginator(posts, 12)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'categories': categories, 'sort': sort, }
    return render(request, 'post/post_list.html', context)


def post_list_comments(request):
    sort = 'comments'
    categories = Category.objects.all()
    posts = Post.objects.annotate(count=Count('comment')).order_by('-count')

    paginator = Paginator(posts, 12)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'categories': categories, 'sort': sort, }
    return render(request, 'post/post_list.html', context)


def post_list_likes(request):
    sort = 'likes'
    categories = Category.objects.all()
    posts = Post.objects.annotate(like_count=Count(
        'like_users')).order_by('-like_count')

    paginator = Paginator(posts, 12)
    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'categories': categories, 'sort': sort, }
    return render(request, 'post/post_list.html', context)


def post_detail(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    post.view_count = post.view_count + 1
    post.save()

    comment_form = comment_forms.CommentForm()
    comment_on_comment_form = comment_forms.CommentOnCommentForm()
    report_comment_form = comment_forms.ReportCommentForm()

    procomments = comment_models.Comment.objects.filter(post=post, type=True).annotate(
        like_count=Count('like_comments')).order_by('-like_count', '-created_at')
    concomments = comment_models.Comment.objects.filter(post=post, type=False).annotate(
        like_count=Count('like_comments')).order_by('-like_count', '-created_at')

    if request.user.is_authenticated():
        procomments_mine = procomments.filter(author=request.user).annotate(
            like_count=Count('like_comments')).order_by('-like_count', '-created_at')
        procomments_exclude = procomments.exclude(author=request.user).annotate(
            like_count=Count('like_comments')).order_by('-like_count', '-created_at')
        concomments_mine = concomments.filter(author=request.user).annotate(
            like_count=Count('like_comments')).order_by('-like_count', '-created_at')
        concomments_exclude = concomments.exclude(author=request.user).annotate(
            like_count=Count('like_comments')).order_by('-like_count', '-created_at')
    else:
        procomments_mine = None
        procomments_exclude = procomments
        concomments_mine = None
        concomments_exclude = concomments

    context = {
        'post': post,
        'procomments_mine': procomments_mine,
        'procomments_exclude': procomments_exclude,
        'concomments_mine': concomments_mine,
        'concomments_exclude': concomments_exclude,
        'comment_form': comment_form,
        'comment_on_comment_form': comment_on_comment_form,
        'report_comment_form': report_comment_form,
    }
    return render(request, 'post/post_detail.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        post_form = PostForm(request.POST, request.FILES)

        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.author = request.user
            post.save()
            messages.success(
                request, '<h4>새로운 채터박스가 만들어졌어요!</h4><p>성공적으로 채터박스가 만들어졌습니다.</p><p>익명으로 많은 사람들에게 공유하고 의견을 받아보세요.</p>')
            return redirect('post:post_detail', post_pk=post.pk)
    else:
        post_form = PostForm()

    context = {
        'post_form': post_form,
    }
    return render(request, 'post/post_create.html', context)


@login_required
def post_update(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if post.author != request.user:
        return redirect('post:post_detail', post_pk=post_pk)

templates/post/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}채터박스. 2지선다 오지랖 커뮤니티{%endblock %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/include/categories.css' %}" />
<link rel="stylesheet" href="{% static 'css/include/sorts.css' %}" />
<link rel="stylesheet" href="{% static 'css/include/pie_chart.css' %}">
<link rel="stylesheet" href="{% static 'css/post/post_list.css' %}" />
{% endblock %}

{% block content %}
<div class="row">
    {% include 'include/category.html' %}
    {% include 'include/sort.html' %}
</div>

<div class="grid row m60">

</div>

<div class="infinite-container row">
    {% for post in posts %}
    <div id="post-{{ post.pk }}" class="infinite-item grid-item">
        {% include 'include/post.html' %}
    </div>
    {% endfor %}
    {% if posts.has_next %}
    <a class="infinite-more-link d-none" href="?page={{ posts.next_page_number }}">더 보기</a>
    {% endif %}
</div>
{% endblock %}

{% block customJS %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
<script src="{% static 'js/include/easy_pie_chart.js' %}"></script>
<script src="{% static 'js/include/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'js/include/infinite.min.js' %}"></script>
<script src="{% static 'js/post/post_detail.js' %}"></script>
<script>
    var $grid = $('.grid').masonry({
        gutter: 15,
        horizontalOrder: true,
        itemSelector: '.grid-item',
    });

    var $items = $('.infinite-container .infinite-item');
    $grid.append($items).masonry('appended', $items);
    $('.grid').masonry();

    var infinite = new Waypoint.Infinite({
        element: $('.infinite-container')[0],
        onBeforePageLoad: function () {
            showModal();
        },
        onAfterPageLoad: function ($items) {
            $('body').loadingModal('destroy');
            customChart();
            var $items = $('.infinite-container .infinite-item');
            $grid.append($items).masonry('appended', $items);
            $('.grid').masonry();
        }
    });

    $(document).ready(function () {
        $('.grid').masonry();
    });
</script>
{% endblock %}

templates/post/post_list_ajax.html
{% for post in posts %}
<div id="post-{{ post.pk }}" class="col-lg-4 col-md-6">
    <div class="grid-item">
        {% include 'include/post.html' %}
    </div>
</div>
{% endfor %}

templates/post/post_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Post modify{% endblock %}

{% block customCSS %}
<link rel="stylesheet" href="{% static 'css/post/post_create.css' %}">
{% endblock %}

{% block content %}
<nav class="lnb navbar">
    <div class="container">
        <a class="nav-icon" href="javascript:history.back()"><img class="nav-icon"
                src="{% static '/img/icons/back.png' %}" /></a>
        <h4>채터박스를 수정 중입니다</h4>
        <ul class="navbar-nav flex-row"></ul>
    </div>
</nav>

<div class="row justify-content-center" id="accordion">
    <form class="tab-content col-md-8 m60 p-0" action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div id="title" class="tab-pane m60 fade show active">
            <div class="item-header">
                <h3>제목을 입력하세요</h3>
                <ol class="indicators">
                    <li class="active"></li>
                    <li></li>
                    <li></li>
                    <li></li>
                </ol>
                <div class="clearfix">
                    <a class="btn btn-fill float-right nextTo2" href="#background" data-toggle="pill">다음으로</a>
                </div>
            </div>

            <div
                class="form-group item-body m60 {{ post_form.title.name }} {% if post_form.title.errors %} has-error {% endif %}">
                {{ post_form.title.label_tag }}
                {{ post_form.title }}
                <h6 id="title_count" class="count">0</h6>
                {% if post_form.title.errors %}
                {% for error in post_form.title.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
                {% endif %}
                <hr />
            </div>

            <div class="item-footer {{ post_form.title.name }}">
                <label>Example</label>
                <img src="/static/img/example-1.png" alt="">
            </div>
        </div>

        <div id="background" class="tab-pane fade m60">
            <div class="item-header">
                <h3>배경을 설명해주세요</h3>
                <ol class="indicators">
                    <li class="active"></li>
                    <li class="active"></li>
                    <li></li>
                    <li></li>
                </ol>
                <div class="clearfix">
                    <a class="btn btn-line float-left" href="#title" data-toggle="pill">이전으로</a>
                    <a class="btn btn-fill float-right nextTo3" href="#opinion" data-toggle="pill">다음으로</a>
                </div>
            </div>

            <div
                class="form-group item-body m60 {{ post_form.background.name }} {% if post_form.background.errors %} has-error {% endif %}">
                {{ post_form.background.label_tag }}
                {{ post_form.background }}
                <h6 id="background_count" class="count">0</h6>
                {% if post_form.background.errors %}
                {% for error in post_form.background.errors %}
                <span class="help-block">{{ error }}</span>
                {% endfor %}
                {% endif %}

                <div class="form-group hide1">
                    <div class="fake-btns fake-btn1">
                        <h6>배경 설명 이미지를 업로드 하려면 클릭하세요.</h6>
                        <h6>(배경 설명 이미지)</h6>
                        <img id="previewHolder1" />
                    </div>
                    {% if post_form.background_image1.errors %}
                    {% for error in post_form.background_image1.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group origin1">
                    {{ post_form.background_image1 }}
                </div>

                <div class="form-group hidden hide2">
                    <div class="fake-btns fake-btn2">
                        <h6>배경 설명 이미지를 업로드 하려면 클릭하세요.</h6>
                        <h6>(배경 설명 이미지)</h6>
                        <img id="previewHolder2" />
                    </div>
                    {% if post_form.background_image2.errors %}
                    {% for error in post_form.background_image2.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group origin2">
                    {{ post_form.background_image2 }}
                </div>

                <div class="form-group hidden hide3">
                    <div class="fake-btns fake-btn3">
                        <h6>배경 설명 이미지를 업로드 하려면 클릭하세요.</h6>
                        <h6>(배경 설명 이미지)</h6>
                        <img id="previewHolder3" />
                    </div>
                    {% if post_form.background_image3.errors %}
                    {% for error in post_form.background_image3.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group origin3">
                    {{ post_form.background_image3 }}
                </div>

                <div class="form-group hidden hide4">
                    <div class="fake-btns fake-btn4">
                        <h6>배경 설명 이미지를 업로드 하려면 클릭하세요.</h6>
                        <h6>(배경 설명 이미지)</h6>
                        <img id="previewHolder4" />
                    </div>
                    {% if post_form.background_image4.errors %}
                    {% for error in post_form.background_image4.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group origin4">
                    {{ post_form.background_image4 }}
                </div>

                <div class="form-group hidden hide5">
                    <div class="fake-btns fake-btn5">
                        <h6>배경 설명 이미지를 업로드 하려면 클릭하세요.</h6>
                        <h6>(배경 설명 이미지)</h6>
                        <img id="previewHolder5" />
                    </div>
                    {% if post_form.background_image5.errors %}
                    {% for error in post_form.background_image5.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group origin5">
                    {{ post_form.background_image5 }}
                </div>
                <hr />
            </div>

            <div class="item-footer {{ post_form.background.name }}">
                <label>Example</label>
                <img src="/static/img/example-2.png" alt="">
            </div>
        </div>

        <div id="opinion" class="tab-pane fade m60">
            <div class="item-header">
                <h3>선택지를 입력해주세요</h3>
                <ol class="indicators">
                    <li class="active"></li>
                    <li class="active"></li>
                    <li class="active"></li>
                    <li></li>
                </ol>
                <div class="clearfix">
                    <a class="btn btn-line float-left" href="#background" data-toggle="pill">이전으로</a>
                    <a class="btn btn-fill float-right nextTo4" href="#option" data-toggle="pill">다음으로</a>
                </div>
            </div>

            <div
                class="item-body m60 {{ post_form.con_title.name }}{% if post_form.pro_title.errors %} has-error {% endif %}{% if post_form.con_title.errors %} has-error {% endif %}">
                <label>Decision</label>
                <div class="form-group">
                    {{ post_form.pro_title }}
                    <h6 id="pro_title_count" class="count">0</h6>
                    {% if post_form.pro_title.errors %}
                    {% for error in post_form.pro_title.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ post_form.con_title }}
                    <h6 id="con_title_count" class="count">0</h6>
                    {% if post_form.con_title.errors %}
                    {% for error in post_form.con_title.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <hr />
            </div>

            <div class="item-footer {{ post_form.con_title.name }}">
                <label>Example</label>
                <img src="/static/img/example-3.png" alt="">
            </div>
        </div>

        <div id="option" class="tab-pane fade m60">
            <div class="item-header">
                <h3>옵션을 선택해주세요</h3>
                <ol class="indicators">
                    <li class="active"></li>
                    <li class="active"></li>
                    <li class="active"></li>
                    <li class="active"></li>
                </ol>
                <div class="clearfix">
                    <a class="btn btn-line float-left" href="#opinion" data-toggle="pill">이전으로</a>
                    <button class="btn btn-fill float-right last" type="submit">게시하기</button>
                </div>
            </div>

            <div class="item-body m60 {{ post_form.background.name }}">
                <div class="form-group">
                    {{ post_form.category.label_tag }}
                    {{ post_form.category }}
                    {% if post_form.category.errors %}
                    {% for error in post_form.category.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="form-group m60">
                    <label>Hashtags</label>
                    {{ post_form.tag }}
                    {% if post_form.tag.errors %}
                    {% for error in post_form.tag.errors %}
                    <span class="help-block">{{ error }}</span>
                    {% endfor %}
                    {% endif %}
                </div>
                <hr />
            </div>

            <div class="item-footer">
                <label>Example</label>
                <img src="/static/img/example-4.png" alt="">
            </div>
        </div>
    </form>
</div>

{% include 'include/toast.html' %}
{% endblock %}

{% block customJS %}
<script src="{% static 'js/include/image_preview.js' %}"></script>
<script src="{% static 'js/post/post_create.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.nextTo2').click(function () {
            for (var counter = 1; counter < 6; counter++) {
                if ($('.origin' + counter + ' a').length) {
                    $('.hide' + counter).show();
                    var thumbPath = $('.origin' + counter + ' a').attr('href');
                    $('#previewHolder' + counter).attr('src', thumbPath);

                    $('.hide' + counter).prepend('<span class="del-image del-' + counter + '">&times;</span>');
                    $('.fake-btn' + counter + ' h6').css('display', 'none');
                    var nextNum = counter + 1;
                    $('.hide' + nextNum).css('display', 'block');
                }
            }
        });

        $('#title_count').text($('#id_title').val().length);
        $('#background_count').text($('#id_background').val().length);
        $('#pro_title_count').text($('#id_pro_title').val().length);
        $('#con_title_count').text($('#id_con_title').val().length);
    });

    $('.clearfix .float-right').click(function () {
        if ($(this).hasClass('btn-fill')) {

        } else {
            $('.toast .content').html('<p>내용을 입력해주세요.</p>');
            $('.toast').toast('show');
        }
    });

    $('.clearfix .btn').click(function () {
        $('.clearfix .btn').removeClass('active');
    });

    $('.last').click(function () {
        if ($(this).is(':disabled')) {
        } else {
            showModal();
        }
    });
</script>
{% endblock %}